services:
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - monitor_net

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command:
      - "--nginx.scrape-uri=http://nginx/status"
    ports:
      - "9181:9113"
    depends_on:
      - nginx
    networks:
      - monitor_net

networks:
  monitor_net:
    driver: bridge
