services:
  nginx_lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_load_balancer
    ports:
      - "80:8080" # Akses aplikasi via load balancer
      - "81:8090" # Status monitoring (ganti 8081 ke 8090 supaya gak bentrok app)
    networks:
      - lb_network

  loadbalancer_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: lb_exporter
    depends_on:
      - nginx_lb
    command:
      - "-nginx.scrape-uri=http://nginx_lb:8090/nginx_status"
    ports:
      - "9113:9113" # Port untuk Prometheus scrape
    networks:
      - lb_network

networks:
  lb_network:
    driver: bridge
