services:
  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app1.conf:/etc/nginx/conf.d/app1.conf
      - ./app2.conf:/etc/nginx/conf.d/app2.conf
      - ./app3.conf:/etc/nginx/conf.d/app3.conf
    ports:
      - "80:80"
    networks:
      - laravel_network

  loadbalancer_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: loadbalancer_exporter
    environment:
      - NGINX_STATUS_URL=http://loadbalancer/status
    ports:
      - "9113:9113"
    networks:
      - laravel_network

networks:
  laravel_network:
    external: true
