services:
  nginx_lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_load_balancer
    ports:
      - "80:8080" # untuk akses aplikasi
      - "81:8081" # untuk status monitoring
    networks:
      - lb_network

  loadbalancer_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: lb_exporter
    depends_on:
      - nginx_lb
    command:
      - "-nginx.scrape-uri=http://nginx_lb:8081/nginx_status"
    ports:
      - "9113:9113"
    networks:
      - lb_network

networks:
  lb_network:
    driver: bridge
